// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;

namespace Steam4NET
{

	[StructLayout(LayoutKind.Sequential,Pack=4)]
	public class ISteamMusic001VTable
	{
		public IntPtr BIsEnabled0;
		public IntPtr BIsPlaying1;
		public IntPtr GetPlaybackStatus2;
		public IntPtr Play3;
		public IntPtr Pause4;
		public IntPtr PlayPrevious5;
		public IntPtr PlayNext6;
		public IntPtr SerVolume7;
		public IntPtr GetVolume8;
		private IntPtr DTorISteamMusic0019;
	};
	
	[InteropHelp.InterfaceVersion("STEAMMUSIC_INTERFACE_VERSION001")]
	public class ISteamMusic001 : InteropHelp.NativeWrapper<ISteamMusic001VTable>
	{
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeBIsEnabled( IntPtr thisptr );
		public Int32 BIsEnabled(  ) 
		{
			return this.GetFunction<NativeBIsEnabled>( this.Functions.BIsEnabled0 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeBIsPlaying( IntPtr thisptr );
		public Int32 BIsPlaying(  ) 
		{
			return this.GetFunction<NativeBIsPlaying>( this.Functions.BIsPlaying1 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetPlaybackStatus( IntPtr thisptr );
		public Int32 GetPlaybackStatus(  ) 
		{
			return this.GetFunction<NativeGetPlaybackStatus>( this.Functions.GetPlaybackStatus2 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativePlay( IntPtr thisptr );
		public Int32 Play(  ) 
		{
			return this.GetFunction<NativePlay>( this.Functions.Play3 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativePause( IntPtr thisptr );
		public Int32 Pause(  ) 
		{
			return this.GetFunction<NativePause>( this.Functions.Pause4 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativePlayPrevious( IntPtr thisptr );
		public Int32 PlayPrevious(  ) 
		{
			return this.GetFunction<NativePlayPrevious>( this.Functions.PlayPrevious5 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativePlayNext( IntPtr thisptr );
		public Int32 PlayNext(  ) 
		{
			return this.GetFunction<NativePlayNext>( this.Functions.PlayNext6 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeSerVolumeF( IntPtr thisptr, float fUnk );
		public Int32 SerVolume( float fUnk ) 
		{
			return this.GetFunction<NativeSerVolumeF>( this.Functions.SerVolume7 )( this.ObjectAddress, fUnk ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetVolume( IntPtr thisptr );
		public Int32 GetVolume(  ) 
		{
			return this.GetFunction<NativeGetVolume>( this.Functions.GetVolume8 )( this.ObjectAddress ); 
		}
		
	};
}
