// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;

namespace Steam4NET
{

	[StructLayout(LayoutKind.Sequential,Pack=4)]
	public class ISteamController001VTable
	{
		public IntPtr Init0;
		public IntPtr Shutdown1;
		public IntPtr RunFrame2;
		public IntPtr GetControllerState3;
		public IntPtr TriggerHapticPulse4;
		public IntPtr SetOverrideMode5;
		private IntPtr DTorISteamController0016;
	};
	
	[InteropHelp.InterfaceVersion("STEAMCONTROLLER_INTERFACE_VERSION")]
	public class ISteamController001 : InteropHelp.NativeWrapper<ISteamController001VTable>
	{
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeInitS( IntPtr thisptr, string pchAbsolutePathToControllerConfigVDF );
		public Int32 Init( string pchAbsolutePathToControllerConfigVDF ) 
		{
			return this.GetFunction<NativeInitS>( this.Functions.Init0 )( this.ObjectAddress, pchAbsolutePathToControllerConfigVDF ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeShutdown( IntPtr thisptr );
		public Int32 Shutdown(  ) 
		{
			return this.GetFunction<NativeShutdown>( this.Functions.Shutdown1 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeRunFrame( IntPtr thisptr );
		public Int32 RunFrame(  ) 
		{
			return this.GetFunction<NativeRunFrame>( this.Functions.RunFrame2 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetControllerStateUS( IntPtr thisptr, UInt32 unControllerIndex, ref SteamControllerState_t pState );
		public Int32 GetControllerState( UInt32 unControllerIndex, ref SteamControllerState_t pState ) 
		{
			return this.GetFunction<NativeGetControllerStateUS>( this.Functions.GetControllerState3 )( this.ObjectAddress, unControllerIndex, ref pState ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeTriggerHapticPulseUEU( IntPtr thisptr, UInt32 unControllerIndex, ESteamControllerPad eTargetPad, UInt16 usDurationMicroSec );
		public void TriggerHapticPulse( UInt32 unControllerIndex, ESteamControllerPad eTargetPad, UInt16 usDurationMicroSec ) 
		{
			this.GetFunction<NativeTriggerHapticPulseUEU>( this.Functions.TriggerHapticPulse4 )( this.ObjectAddress, unControllerIndex, eTargetPad, usDurationMicroSec ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeSetOverrideModeS( IntPtr thisptr, string pchMode );
		public void SetOverrideMode( string pchMode ) 
		{
			this.GetFunction<NativeSetOverrideModeS>( this.Functions.SetOverrideMode5 )( this.ObjectAddress, pchMode ); 
		}
		
	};
}
